# AIFFEL코드 연습    

https://sbabasic.aiffel.io/steps/189

## 1. 9/8(화) 깜짝퀴즈    
두 정수 a, b가 주어졌을 때 a와 b 사이에 속한 모든 정수의 합을 리턴하는 함수, solution을 완성하세요.
예를 들어 a = 3, b = 5인 경우, 3 + 4 + 5 = 12이므로 12를 리턴합니다.
앞으로 정답의 형태는 오늘 배운 함수로!! 진행해주시면 됩니다. 예를 들어 위의 문제 같은 경우는 입력값을 a, b로 받고 리턴은 12를 한다했으므로
def solution(a, b):
    ...
    return answer
의 꼴로 짜주시면 됩니다! 그러니 solution(3, 5) 의 결과는 12가 나와야겠죠?
+++
결과를 .py 포맷으로 저장하시고 개인 github repository에 업로드하는 것까지 해봅시다!

In [1]:
## 풀이1

def solution(a,b):
    answer = a
    while a<b:
        a +=1
        answer +=a
    return answer
        

In [2]:
solution(3,5)

12

In [10]:
## 풀이2

def solution(a,b):
    if a>=b:
        answer=a
    else:
        answer=a
        while a<b:
            a +=1
            answer +=a
    return answer

In [11]:
solution(3,5)

12

## 2. 9/9(수) 깜짝퀴즈

In [1]:
0.1 + 0.2 - 0.3

5.551115123125783e-17

In [2]:
0.1 + 0.2

0.30000000000000004

In [3]:
0.0

0.0

In [5]:
bool(None)

False

In [7]:
## 피보나치킨 함수 만들기 F3-23

def fibonacci(n):
    if n<=2:
        number=1
    else:
        number = fibonacci(n-1) + fibonacci(n-2)
    return number

In [8]:
fibonacci(5)

5

In [13]:
fibonacci(20)

6765

In [14]:
## 메모이제이션(memoization) 프로그래밍에서 중간밧을 계산해서 기억해두는 방법

memory= {1:1, 2:1}

def fibonacci(n):
    if n in memory:
        number = memory[n]
    else:
        number = fibonacci(n-1) + fibonacci(n-2)
        memory[n] = number
    return number

In [15]:
fibonacci(5)

5

In [16]:
memory

{1: 1, 2: 1, 3: 2, 4: 3, 5: 5}

In [17]:
import struct
def float_to_bin(num):
    return format(struct.unpack('!I', struct.pack('!f', num))[0], '032b')

In [18]:
float_to_bin(1)

'00111111100000000000000000000000'

# 6-3 최종코드

In [12]:
def numbers():
    X=[]
    while True:
        number = input("Enter a number (<Enter key> to quit)") 
        while number !="":
            try:
                x = float(number)
                X.append(x)
            except ValueError:
                print('>>> NOT a number! Ignored..')
            number = input("Enter a number (<Enter key> to quit)")
        if len(X) > 1:
            return X

def median(nums): 
    nums.sort()
    size = len(nums)
    p = size // 2
    if size % 2 == 0:
        pr = p
        pl = p-1
        mid = float((nums[pl]+nums[pr])/2)
    else:
        mid = nums[p]
    return mid

def means(nums):
    total = 0.0
    for i in range(len(nums)):
        total = total + nums[i]
    return total / len(nums)

def std_dev(nums, avg):
   texp = 0.0
   for i in range(len(nums)):
       texp = texp + (nums[i] - avg) ** 2
   return (texp/(len(nums)-1)) ** 0.5

def main():
    X = numbers()
    med = median(X)
    avg = means(X)
    std = std_dev(X, avg)
    print("당신이 입력한 숫자{}의 ".format(X))
    print("중앙값은{}, 평균은{}, 표준편차는{}입니다.".format(med, avg, std))

if __name__ == '__main__':
    main()
    

Enter a number (<Enter key> to quit)2
Enter a number (<Enter key> to quit)3
Enter a number (<Enter key> to quit)4
Enter a number (<Enter key> to quit)5
Enter a number (<Enter key> to quit)
당신이 입력한 숫자[2.0, 3.0, 4.0, 5.0]의 
중앙값은3.5, 평균은3.5, 표준편차는1.2909944487358056입니다.


# 6.5 Numpy 주요기능

In [2]:
import numpy as np

print([1,2]+[3,4])
print([1,2]+3)

[1, 2, 3, 4]


TypeError: can only concatenate list (not "int") to list

In [3]:
import numpy as np
print(np.array([1,2])+np.array([3,4]))
print(np.array([1,2])+3)

[4 6]
[4 5]


In [4]:
# 의사 난수를 생성하는 예제입니다. 여러번 실행해 보세요.

print(np.random.random())   # 0에서 1사이의 실수형 난수 하나를 생성합니다. 

print(np.random.randint(0,10))   # 0~9 사이 1개 정수형 난수 하나를 생성합니다. 

print(np.random.choice([0,1,2,3,4,5,6,7,8,9]))   # 리스트에 주어진 값 중 하나를 랜덤하게 골라줍니다.

0.41852896292483877
9
7


In [5]:
# 아래 2가지는 기능면에서 동일합니다. 원소의 순서를 임의로 뒤바꾸어 줍니다. 

print(np.random.permutation(10))   
print(np.random.permutation([0,1,2,3,4,5,6,7,8,9]))

[7 4 5 6 8 3 0 2 9 1]
[2 4 7 5 1 6 9 8 0 3]


In [6]:
# 아래 기능들은 어떤 분포를 따르는 변수를 임의로 표본추출해 줍니다. 

# 이것은 정규분포를 따릅니다.
print(np.random.normal(loc=0, scale=1, size=5))    # 평균(loc), 표준편차(scale), 추출개수(size)를 조절해 보세요.

# 이것은 균등분포를 따릅니다. 
print(np.random.uniform(low=-1, high=1, size=5))  # 최소(low), 최대(high), 추출개수(size)를 조절해 보세요.

[-0.33129736  0.32758621  0.95171034 -0.28183026 -0.07483665]
[-0.83552349  0.47434357 -0.44134453 -0.82321478 -0.05827091]


## 6.5(8) 전치행렬

In [7]:
A = np.arange(24).reshape(2,3,4)
print(A)               # A는 (2,3,4)의 shape를 가진 행렬입니다. 

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [8]:
print(A.T)            # 이것은 A의 전치행렬입니다. 

[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [13]:
x= np.arange(3).reshape(1,3)
print(x)

[[0 1 2]]


In [15]:
print(x.T)

[[0]
 [1]
 [2]]


In [16]:
print(A.T.shape)

(4, 3, 2)


In [18]:
x= np.ones((4,3,2))
print(x)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


# 6-10. 간단한 딕셔너리(dictionary)를 활용한 판타지 게임 logic 설계

In [19]:
treasure_box = {'rope':2, 
                'apple':10, 
                'torch': 6, 
                'gold coin': 50, 
                'knife': 1, 
                'arrow': 30}

In [20]:
coin_per_treasure = {'rope':1,
        'apple':2,
        'torch': 2,
        'gold coin': 5, 
        'knife': 30,
        'arrow': 1}


In [21]:
treasure_box = {'rope': {'coin': 1, 'pcs': 2},
                'apple': {'coin': 2, 'pcs': 10},
                'torch': {'coin': 2, 'pcs': 6},
                'gold coin': {'coin': 5, 'pcs': 50},
                'knife': {'coin': 1, 'pcs': 30}}
treasure_box['rope']

{'coin': 1, 'pcs': 2}

In [25]:
def total_silver(treasure_box, coin_per_treasure):
    ## type your code
    total_coin = 0
    for treasure in treasure_box:
        coin = coin_per_treasure[treasure] * treasure_box[treasure]['pcs']
        print("{} : {}coins/pcs * {}pcs = {} coins".format(
          treasure, coin_per_treasure[treasure], treasure_box[treasure]['pcs'], coin))
        total_coin += coin
    print('total_coin : ', total_coin)

In [27]:
 print('total_coin : ', total_coin)

NameError: name 'total_coin' is not defined

In [30]:
def display_stuff(treasure_box):
    ## type your code
    print("Congraturation!! you got a treasure box!!")
    for treasure in treasure_box:
             print("You have {} {}pcs".format(treasure, treasure_box[treasure]['pcs']))

def total_silver(treasure_box, coin_per_treasure):
    ## type your code
    total_coin = 0
    for treasure in treasure_box:
        coin = coin_per_treasure[treasure] * treasure_box[treasure]['pcs']
        print("{} : {}coins/pcs * {}pcs = {} coins".format(
          treasure, coin_per_treasure[treasure], treasure_box[treasure]['pcs'], coin))
        total_coin += coin
    print('total_coin : ', total_coin)
display_stuff(treasure_box)
total_silver(treasure_box, coin_per_treasure)

Congraturation!! you got a treasure box!!
You have rope 2pcs
You have apple 10pcs
You have torch 6pcs
You have gold coin 50pcs
You have knife 30pcs
rope : 1coins/pcs * 2pcs = 2 coins
apple : 2coins/pcs * 10pcs = 20 coins
torch : 2coins/pcs * 6pcs = 12 coins
gold coin : 5coins/pcs * 50pcs = 250 coins
knife : 30coins/pcs * 30pcs = 900 coins
total_coin :  1184


# 6-13 pandas 실습

In [31]:
import pandas as pd
import os

csv_path = os.getenv("HOME") + "/workplace/covid19_italy_region.csv"
data = pd.read_csv(csv_path)
type(data)

pandas.core.frame.DataFrame

In [32]:
data.columns

Index(['SNo', 'Date', 'Country', 'RegionCode', 'RegionName', 'Latitude',
       'Longitude', 'HospitalizedPatients', 'IntensiveCarePatients',
       'TotalHospitalizedPatients', 'HomeConfinement', 'CurrentPositiveCases',
       'NewPositiveCases', 'Recovered', 'Deaths', 'TotalPositiveCases',
       'TestsPerformed'],
      dtype='object')

In [33]:
data.drop([ 'Latitude','Longitude','Country','Date','SNo', 'HospitalizedPatients','RegionCode','IntensiveCarePatients','TotalHospitalizedPatients','HomeConfinement'
], axis=1, inplace=True)

data.corr()

CurrentPositiveCases  NewPositiveCases  Recovered  \
CurrentPositiveCases              1.000000          0.892083   0.903833   
NewPositiveCases                  0.892083          1.000000   0.760710   
Recovered                         0.903833          0.760710   1.000000   
Deaths                            0.937337          0.775184   0.986324   
TotalPositiveCases                0.990303          0.865022   0.954026   
TestsPerformed                    0.886860          0.755386   0.741827   

                        Deaths  TotalPositiveCases  TestsPerformed  
CurrentPositiveCases  0.937337            0.990303        0.886860  
NewPositiveCases      0.775184            0.865022        0.755386  
Recovered             0.986324            0.954026        0.741827  
Deaths                1.000000            0.975269        0.761221  
TotalPositiveCases    0.975269            1.000000        0.855529  
TestsPerformed        0.761221            0.855529        1.000000

# 7-5 클래스의 기본문법 속성과 메소드

In [85]:
class Car:
    color = 'red'
    category = 'sports car'

    def drive(self):
        print("I'm driving")

    def accel(self, speed_up, current_speed=10):
        self.speed_up = speed_up
        self.current_speed = current_speed + speed_up
        print("speed up", self.speed_up, "driving at", self.current_speed)

In [36]:
print(Car())

In [37]:
mycar=Car()

In [38]:
print(mycar.color)

red


In [40]:
print(mycar.category)

sports car


In [41]:
mycar.drive()

I'm driving


In [43]:
mycar.accel(0,10)

speed up 0 driving at 10


In [44]:
Car.drive(mycar)

I'm driving


In [47]:
Car.accel(mycar).10

SyntaxError: invalid syntax (<ipython-input-47-4588fcac7585>, line 1)

# 7-9. 클래스 조금 더 알아보기

In [2]:
class Car:
    Manufacture = "India"

    def __init__(self, color='red', category='sedan'):
        self.color = color
        self.category = category

    def drive(self):
        print("I'm driving")

    def accel(self, speed_up, current_speed=10):
        self.speed_up = speed_up
        self.current_speed = current_speed + self.speed_up
        print("speed up", self.speed_up, "driving at", self.current_speed)

In [3]:
class NewCar(Car):
    def __init__(self, color, category, maker):
        super().__init__(color, category)
        self.maker = maker
        self.boost = {1 : 0, 2 : 30, 3 : 50}

    def fly(self):
        print("I'm flying!! This is the new car!!")

    def accel(self, speed_up, level=1, current_speed=10):
        self.speed_up = speed_up + self.boost[level]
        self.current_speed = current_speed + self.speed_up
        print("speed up", self.speed_up, "driving at", self.current_speed)

In [4]:
newcar= NewCar('blue', 'sedan', 'kia')

In [6]:
newcar.accel(5,3)

speed up 55 driving at 65


In [97]:
newcar.fly()

I'm flying!! This is the new car!!


# 7.11 n면체 주사위 만들기 (2) 주 프로그램 - main 함수

In [7]:
def main():
    n = get_inputs()
    mydice=FunnyDice(n)
    mydice.throw()
    print("행운의 숫자는?{}". format(mydice.getval()))

In [13]:
class FunnyDice:
    def __init__(self,n):
        self.n=n
        
    def throw(self):
        pass
    def getval(self):
        pass
    def setval(self, val):
        pass

In [14]:
from random import randrange

class FunnyDice:
    def __init__(self, n=6):
        self.n = int(n)
        self.numbers = list(range(1, n+1))
        self.index = randrange(0, self.n)
        self.val = self.numbers[self.index]

In [15]:
from random import randrange

class FunnyDice:
    def throw(self):
        self.index = randrange(0, self.n)
        self.val = self.numbers[self.index]
    
    def getval(self):
        return self.val

In [16]:
from random import randrange

class FunnyDice:    
    def setval(self, val:int):
        if val <= self.n:
            self.val = val
        else:
            print("주사위에 없는 숫자입니다. 주사위는 1 ~ {0}까지 있습니다. ".format(self.n))
            raise error

In [17]:
###전체코드
class FunnyDice:
    def __init__(self, n=6):
        self.n = int(n)
        self.numbers = list(range(1, n+1))
        self.index = randrange(0, self.n)
        self.val = self.numbers[self.index]

    def throw(self):
        self.index = randrange(0, self.n)
        self.val = self.numbers[self.index]

    def getval(self):
        return self.val

    def setval(self, val):
        if val <= self.n:
            self.val = val
        else:
            print("주사위에 없는 숫자입니다. 주사위는 1 ~ {0}까지 있습니다. ".format(self.n))
            raise error

In [19]:
FunnyDice= FunnyDice("3)

SyntaxError: EOL while scanning string literal (<ipython-input-19-4a09e28a0738>, line 1)

# 8.3 파이썬을 더 잘 사용해보자

In [20]:
my_list = ['a','b','c','d']

# 인자로 받은 리스트로부터 데이터를 하나씩 가져오는 제너레이터를 리턴하는 함수
def get_dataset_generator(my_list):
    result_list = []
    for i in range(2):
        for j in my_list:
            yield (i, j)
            print('>>  1 data loaded..')

In [23]:
dataset_generator = get_dataset_generator(my_list)
for X, y in dataset_generator:
    print(X, y)

0 a
>>  1 data loaded..
0 b
>>  1 data loaded..
0 c
>>  1 data loaded..
0 d
>>  1 data loaded..
1 a
>>  1 data loaded..
1 b
>>  1 data loaded..
1 c
>>  1 data loaded..
1 d
>>  1 data loaded..


In [25]:
a = 10
b = 2
try:
    #실행 코드
    print(a/b)
		
except:
    #에러가 발생했을 때 처리하는 코드
    print('에러가 발생했습니다.')

5.0


In [38]:
import time

num_list = ['p1','p2', 'p3', 'p4']
start = time.time()

def count(name):
    for i in range(0, 100000000):
        a=3
        
    print("finish : ",name)

for num in num_list:
    count(num)

print("time :", time.time() - start)

finish :  p1
finish :  p2
finish :  p3
finish :  p4
time : 6.455041170120239


In [36]:
num_list = ['p1','p2', 'p3', 'p4', 'a1']
start = time.time()

In [37]:
for num in num_list:
    count(num)

print("time :", time.time() - start)

finish :  p1
finish :  p2
finish :  p3
finish :  p4
finish :  a1
time : 9.534203290939331


# 8.6 함수 사용하기

In [1]:
list_data = [10, 20, 30, 40]
list_data2 = [20, 30, 40, 50]

In [3]:
len(list_data)

4

In [6]:
def list_mul(x):
     return x * 2

result = list(map(list_mul, [1, 2, 3]))
print(result)

[2, 4, 6]


In [7]:
result = list(map(lambda i: i * 2 , [1, 2, 3]))
print(result)

[2, 4, 6]
